# -*- coding: utf-8 -*-
"""eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aa97NUjWIRoAo8O4comDkT21Tctmoe-3
"""

# eda.py
import pandas as pd

def eda(input_path):
    data = pd.read_csv(input_path)

    # Example insights
    insights = [
        f"Insight 1: Average age of passengers is {data['Age'].mean()}",
        f"Insight 2: Median fare of passengers is {data['Fare'].median()}",
        f"Insight 3: Number of male and female passengers: {data['Sex'].value_counts().to_dict()}"
    ]

    # Save insights as text files
    for i, insight in enumerate(insights):
        with open(f'/home/doc-bd-a1/eda-in-{i+1}.txt', 'w') as f:
            f.write(insight)

if __name__ == "__main__":
    eda('/home/doc-bd-a1/res_dpre.csv')