# -*- coding: utf-8 -*-
"""load.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aa97NUjWIRoAo8O4comDkT21Tctmoe-3
"""

# load.py
import sys
import pandas as pd

def load_data(file_path):
    data = pd.read_csv(file_path)
    print("Data loaded successfully.")
    data.to_csv('/home/doc-bd-a1/temp_data.csv', index=False)

if __name__ == "__main__":
    load_data(sys.argv[1])