# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aa97NUjWIRoAo8O4comDkT21Tctmoe-3
"""

# model.py
import pandas as pd
from sklearn.cluster import KMeans

def kmeans_model(input_path, output_path):
    data = pd.read_csv(input_path)

    # Select features for clustering
    features = data[['Age', 'Fare']].dropna()

    # Apply K-means clustering
    kmeans = KMeans(n_clusters=3)
    data['cluster'] = kmeans.fit_predict(features)

    # Count the number of records in each cluster
    counts = data['cluster'].value_counts()

    # Save cluster counts to a file
    with open(output_path, 'w') as f:
        for cluster, count in counts.items():
            f.write(f'Cluster {cluster}: {count} records\n')

if __name__ == "__main__":
    kmeans_model('/home/doc-bd-a1/res_dpre.csv', '/home/doc-bd-a1/k.txt')