# -*- coding: utf-8 -*-
"""vis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aa97NUjWIRoAo8O4comDkT21Tctmoe-3
"""

# vis.py
import pandas as pd
import matplotlib.pyplot as plt

def create_visualization(input_path):
    data = pd.read_csv(input_path)

    # Plot a histogram for the 'Age' column
    plt.hist(data['Age'], bins=10, color='blue', alpha=0.7)
    plt.title('Age Distribution of Titanic Passengers')
    plt.xlabel('Age')
    plt.ylabel('Frequency')
    plt.savefig('/home/doc-bd-a1/vis.png')

if __name__ == "__main__":
    create_visualization('/home/doc-bd-a1/res_dpre.csv')